services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn recharges.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
